import Head from "next/head"
import PopularSubs from "~/components/subs/PopularSubs"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
			</Head>

			<PopularSubs />
		</>
	)
}
